// =========================================================================
// Logicodex v1.44 — Freestanding Startup Code (crt0)
//
// _start: Entry point for freestanding (bare-metal) execution.
// Runs before main() — initializes the environment that main() expects.
//
// Steps:
//   1. Set stack pointer (2MB)
//   2. Zero BSS segment (uninitialized statics → 0)
//   3. Copy data segment (ROM → RAM)
//   4. Call main()
//   5. Halt (infinite loop — no OS to return to)
//
// Linked at 0x100000 (1MB) via linker script.
// Stack at 0x200000 (2MB), grows downward.
// =========================================================================

/// Stack top address — 2MB into physical memory.
/// Stack grows downward from here toward 1MB (code region).
const STACK_TOP: u64 = 0x200000;

/// Entry point for freestanding targets.
/// This is the very first code that runs after bootloader hands control.
///
/// # Safety
/// Called only once at boot. Must not return.
#[cfg(target_os = "none")]
#[unsafe(no_mangle)]
pub extern "C" fn _start() -> ! {
    unsafe {
        // Step 1: Set stack pointer
        // rsp = STACK_TOP (2MB), grows downward
        core::arch::asm!(
            "mov rsp, {stack}",
            stack = in(reg) STACK_TOP,
            options(nomem, preserves_flags)
        );

        // Step 2: Zero BSS segment
        // BSS = uninitialized static variables — must be zero before use
        let bss_start = &__bss_start as *const u8 as *mut u8;
        let bss_end = &__bss_end as *const u8 as *mut u8;
        let bss_size = bss_end as usize - bss_start as usize;
        core::ptr::write_bytes(bss_start, 0, bss_size);

        // Step 3: Copy data segment from LMA (load memory address) to VMA
        // Data = initialized static variables — copied from ROM/flash to RAM
        let data_start = &__data_start as *const u8 as *mut u8;
        let data_end = &__data_end as *const u8 as *mut u8;
        let data_lma = &__data_lma as *const u8;
        let data_size = data_end as usize - data_start as usize;
        if data_size > 0 {
            core::ptr::copy_nonoverlapping(data_lma, data_start, data_size);
        }

        // Step 4: Call the user program's main function
        // For Logicodex-compiled programs, this is the entry point
        // generated by compile_v130() with target.entry_symbol() = "_start"
        //
        // Note: The actual main() is generated by Logicodex codegen.
        // This _start is for the Logicodex compiler itself when running
        // as a freestanding binary (e.g., self-hosted compiler).
        //
        // For Logicodex-generated programs, the compiler inserts its own
        // _start or relies on the bootloader/multiboot entry point.
        extern "Rust" {
            fn main() -> i32;
        }
        let _ = main();

        // Step 5: Halt — no OS to return to
        halt()
    }
}

/// Halt the CPU — infinite loop with interrupts disabled.
/// Used when the program returns from main() or panics.
#[cfg(target_os = "none")]
pub fn halt() -> ! {
    unsafe {
        loop {
            core::arch::asm!("cli; hlt", options(nomem, nostack, preserves_flags));
        }
    }
}

/// Halt without disabling interrupts — for non-fatal situations.
#[cfg(target_os = "none")]
pub fn halt_interruptible() -> ! {
    unsafe {
        loop {
            core::arch::asm!("hlt", options(nomem, nostack, preserves_flags));
        }
    }
}

// ─── Linker Script Symbols ───
// These are defined by the linker script (lib/linker_scripts/x86_64-freestanding.ld).
// They mark the boundaries of BSS and DATA segments.

extern "C" {
    /// Start of BSS segment (zero-initialized statics)
    static __bss_start: u8;
    /// End of BSS segment
    static __bss_end: u8;
    /// Start of DATA segment (initialized statics, in RAM)
    static __data_start: u8;
    /// End of DATA segment
    static __data_end: u8;
    /// Load Memory Address of DATA (in ROM/flash)
    static __data_lma: u8;
}

// ─── Hosted fallback ───
// When not building for bare metal, these are no-ops.

#[cfg(not(target_os = "none"))]
pub fn halt() -> ! {
    std::process::exit(1)
}

#[cfg(not(target_os = "none"))]
pub fn halt_interruptible() -> ! {
    std::process::exit(0)
}

// =========================================================================
// Tests (compile-time only — can't run in test environment)
// =========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn stack_top_is_reasonable() {
        assert!(STACK_TOP > 0x100000, "Stack must be above code at 1MB");
        assert!(STACK_TOP < 0x100000000, "Stack must be below 4GB");
    }

    #[test]
    fn stack_has_room() {
        // Stack from 1MB (code end) to 2MB = 1MB of stack space
        let stack_size = STACK_TOP - 0x100000;
        assert_eq!(stack_size, 0x100000, "Stack size must be 1MB");
    }

    #[test]
    fn linker_symbols_exist_at_compile_time() {
        // Just verify the symbols are declared — linker will resolve them
        let _ = stringify!(__bss_start);
        let _ = stringify!(__bss_end);
        let _ = stringify!(__data_start);
        let _ = stringify!(__data_end);
        let _ = stringify!(__data_lma);
    }
}
